version: '3'

services:
  bff:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
    environment:
      - FIREBASE_SERVICE_ACCOUNT_JSON=/app/secure/serviceAccountKey-gcp.json
      - FIREBASE_CONFIG_JSON=/app/secure/config-gcp.js
